# NZ : length of qlabels
# N : Dimension of CGT 
# I defined it to cover arbitrary CGT dimensions
# but in my calculation, it is 3 for almost every case
# 2 for rare cases (1j-symbol)
# Clebsch-Gordan tensor in block-sparse format
# Each block is a dense array, and the blocks are indexed by weights
# RT : Number type of irreps, CT : Number type of CGT
"""
    CGT

A block-sparse Clebsch-Gordan tensor. `qlabels` gives one irrep label per leg;
`blocks` maps weight-label tuples to dense coefficient arrays; the final block
axis is outer multiplicity; `nfactor` stores exact normalization factors; and
`dir` records incoming/outgoing leg directions. `size_byte` is cache metadata.

# Fields

- `qlabels`: irrep q-label of every CGT leg.
- `blocks`: nonzero coefficient blocks keyed by weight-label tuples.
- `nfactor`: exact block normalization factors.
- `dir`: `+`/`-` direction convention for each leg.
- `size_byte`: cached memory footprint for LRU eviction.
"""
struct CGT{S<:NonabelianSymm, CT<:Number, NZ, N}
    qlabels::NTuple{N, NTuple{NZ, Int}} # qlabels for each leg
    # Nonzero blocks of CGT. 
    # Key is a tuple of qlabels, value is the corresponding array
    # Each array has rank N+1, the last dimension is outer multiplicity
    blocks::Dict{NTuple{N, NTuple{NZ, Int}}, Array{CT}}

    nfactor::Vector{Rational{BigInt}} 
    dir::NTuple{N, Char}
    # Cached memory footprint in bytes, computed once at construction for LRU cache eviction by size
    size_byte::Int
    
    function CGT{S, CT, NZ, N}(qlabels, blocks, nfactor, dir, size_byte::Int=0) where {S, CT, NZ, N}
        if size_byte == 0
            obj = new{S, CT, NZ, N}(qlabels, blocks, nfactor, dir, 0)
            size_byte = Base.summarysize(obj)
        end
        new{S, CT, NZ, N}(qlabels, blocks, nfactor, dir, size_byte)
    end
end


"""
    load_cg3blk(::Type{S}, ::Type{CT}, qlabels_in, qlabels_out) -> Dict

Load CG3 block dictionaries and normalization factors for several outputs.

`qlabels_in` is the input pair, `qlabels_out` is the requested output qlabel
vector, `S` selects symmetry, and `CT` is the CGT coefficient type. The return
value maps each requested output qlabel to `(blocks, nfactor)`, where `blocks`
is the CGT's weight-block dictionary and `nfactor` is its OM normalization
vector. Missing CGTs are generated by `getNsave_cg3`.
"""
function load_cg3blk(::Type{S},
    ::Type{CT},
    qlabels_in::NTuple{2, NTuple{NZ, Int}},
    qlabels_out::Vector{NTuple{NZ, Int}}) where {S<:NonabelianSymm, NZ, CT<:Number}

    cg3s = getNsave_cg3(S, CT, qlabels_in, qlabels_out)
    return Dict(q => (cg3s[q].blocks, cg3s[q].nfactor) for q in qlabels_out)
end

"""
    getNsave_cg3(S, CT, qlabels_in, qlabels_out)

Load or generate CG3 tensors coupling `qlabels_in=(q1,q2)` to requested outputs.

`S` selects the non-Abelian family and `CT` the CGT scalar type. `qlabels_in`
may be unsorted; the cache key uses the sorted pair and the result is permuted
back if the original order was reversed. `qlabels_out` is the vector of output
qlabels to return. The result is `Dict{qout,CGT}`. Missing entries are generated
and saved through the configured SQLite cache. Input qlabel widths must match
`nzops(S)`.
"""
function getNsave_cg3(::Type{S}, 
    ::Type{CT}, 
    qlabels_in::NTuple{2, NTuple{NZ, Int}},
    qlabels_out::Vector{NTuple{NZ, Int}}) where {S<:NonabelianSymm, CT<:Number, NZ}

    @assert NZ == nzops(S)
    dir = ['+', '+', '-']
    qlabels_in_sorted = Tuple([minmax(qlabels_in[1], qlabels_in[2])...])
    permute = qlabels_in[1] > qlabels_in[2]

    cg3s = Dict{NTuple{NZ, Int}, CGT{S, CT, NZ, 3}}()
    remain_qs = Vector{NTuple{NZ, Int}}()
    # Find as many CG3s as possible from saved files
    for qout in qlabels_out
        qlabels_sorted = Tuple([qlabels_in_sorted..., qout])
        cg3 = load_cgt_sqlite(S, CT, qlabels_sorted)
        if !isnothing(cg3) cg3s[qout] = cg3
        else push!(remain_qs, qout) end
    end

    # Generate missing CG3s
    if !isempty(remain_qs)
        new_cg3s = generate_every_CGT(S, CT, CT, qlabels_in_sorted, remain_qs)
        for q in remain_qs 
            @assert haskey(new_cg3s, q)
            cg3s[q] = new_cg3s[q]
        end
    end
    
    for q in remain_qs @assert haskey(cg3s, q) end

    if permute
        for (q, cg3) in cg3s
            new_blocks = Dict{NTuple{3, NTuple{NZ, Int}}, Array{CT}}()
            for k in keys(cg3.blocks)
                new_key = (k[2], k[1], k[3])
                new_blocks[new_key] = permutedims(cg3.blocks[k], (2, 1, 3, 4))
            end
            cg3s[q] = CGT{S, CT, NZ, 3}(Tuple([qlabels_in..., q]), 
            new_blocks, cg3.nfactor, Tuple(dir), cg3.size_byte)
        end
    end
    return cg3s
end
